spring.datasource.url: jdbc:mysql://localhost:3306/blog
spring.datasource.username: root
spring.datasource.password: qwer12#$
spring.jpa.hibernate.ddl-auto: validate
#spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#spring.jpa.show-sql: false


#GET /api/init
blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005